### ISSUE TITLE
Missing transpiled file: web-fcs-api-base.js

### ISSUE THREAD

**Issue by atkulp** [foss-card-games/Solitairey#12]
When trying to run your hosted version (https://foss-card-games.github.io/Solitairey/), I get a 404 on web-fcs-api-base.js, and sure enough it's in the TS folder, but not the JS folder.

**Comment by shlomif** [comment]
thanks for the report. no promises, but i'll try2fix it. @atkulp

**Comment by shlomif** [comment]
@atkulp : https://foss-card-games.github.io/Solitairey/ seems2work fine now. please test.

**Comment by atkulp** [comment]
Awesome! Thanks for that. Very nice work!

**Comment by shlomif** [comment]
@atkulp : yw. can the issue be closed?

**Comment by atkulp** [comment]
you bet! Thanks for your prompt attention to it.
